### ISSUE TITLE
Downgrading node can cause policy packs to fail with funny errors

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-policy#121]
For example, see the following output.

We might want to have a `policy install` or `policy install --refresh` subcommand that force-re/installs these plugins to "fix" issues like this.

Plugins written in node are generally probably susceptible to the same errors.

```sh
clstokes@Camerons-MacBook-Pro aws-ts-webserver % pulumi preview
Previewing update (dev):
     Type                 Name                       Plan     Info
     pulumi:pulumi:Stack  demo-aws-ts-webserver-dev           16 messages

Diagnostics:
  pulumi:pulumi:Stack (demo-aws-ts-webserver-dev):
    error: [runtime] Running program '/Users/clstokes/.pulumi/policies/pulumi-analyzer-ec2-v36' failed with an unhandled exception:
        Error: Failed to load gRPC binary module because it was not installed for the current system
    Expected directory: node-v64-darwin-x64-unknown
    Found: [node-v72-darwin-x64-unknown]
    This problem can often be fixed by running "npm rebuild" on the current system
    Original error: Cannot find module '/Users/clstokes/.pulumi/policies/pulumi-analyzer-ec2-v36/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node'
        at Object.<anonymous> (/Users/clstokes/.pulumi/policies/pulumi-analyzer-ec2-v36/node_modules/grpc/src/grpc_extension.js:53:17)
        at Module._compile (internal/modules/cjs/loader.js:778:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
        at Module.require (internal/modules/cjs/loader.js:692:17)
        at require (internal/modules/cjs/helpers.js:25:18)
        at Object.<anonymous> (/Users/clstokes/.pulumi/policies/pulumi-analyzer-ec2-v36/node_modules/grpc/src/client_interceptors.js:144:12)
        at Module._compile (internal/modules/cjs/loader.js:778:30)

Permalink: https://app.pulumi.com/clstokes/demo-aws-ts-webserver/dev/previews/923b67aa-c74e-463e-8430-e2203455285d
error: policy pack ec2 failed to start because of an internal error: could not read plugin [/usr/local/bin/pulumi-analyzer-policy] stdout: EOF
clstokes@Camerons-MacBook-Pro aws-ts-webserver %
```

**Comment by tyler-dunkel** [comment]
@justinvp do you know if this is still the case?

**Comment by justinvp** [comment]
Probably. When installing a policy pack written in Node.js, as part of installing the policy pack, it will run `npm install` which will pull down the policy pack's dependencies. If the global version of node on the machine is downgraded, I suppose it's possible those already installed dependencies won't work with the downgraded version of node, e.g. if they were assuming a more recent version of `node` and now `node` is older. It's also possible this is rare for more recent versions of node, unless those dependencies are using bleeding edge features of Node.
