### ISSUE TITLE
policy-pack flag doesn't work with `~` for home directory

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-policy#125]
The `--policy-pack` flag doesn't work when using `~/path...` to specify a path to the policy pack - it fails with an error.

```
clstokes@Camerons-MacBook-Pro aws-ts-webserver % pulumi preview --policy-pack=policies
Previewing update (dev):

     Type                                    Name                       Plan
 +   pulumi:pulumi:Stack                     demo-aws-ts-webserver-dev  create
 +   ├─ awsx:x:ec2:Vpc                       web-vpc                    create
...

Resources:
    + 12 to create

Permalink: https://app.pulumi.com/clstokes/demo-aws-ts-webserver/dev/previews/6ac825bc-9f8b-40b5-8a9a-9d4d1cd2bd7a
clstokes@Camerons-MacBook-Pro aws-ts-webserver % pulumi preview --policy-pack=/Users/clstokes/cc/pulumi/sales/demos/aws-ts-webserver/policies
Previewing update (dev):

     Type                                    Name                       Plan
 +   pulumi:pulumi:Stack                     demo-aws-ts-webserver-dev  create
 +   ├─ awsx:x:ec2:Vpc                       web-vpc                    create
...

Resources:
    + 12 to create

Permalink: https://app.pulumi.com/clstokes/demo-aws-ts-webserver/dev/previews/930934bd-25e0-4c42-9ee8-f2db35f8a000
clstokes@Camerons-MacBook-Pro aws-ts-webserver % pulumi preview --policy-pack=~/cc/pulumi/sales/demos/aws-ts-webserver/policies
Previewing update (dev):

     Type                 Name                       Plan     Info
     pulumi:pulumi:Stack  demo-aws-ts-webserver-dev           1 error; 13 messages

Diagnostics:
  pulumi:pulumi:Stack (demo-aws-ts-webserver-dev):
    We failed to locate the entry point for your program: /Users/clstokes/cc/pulumi/sales/demos/aws-ts-webserver/~/cc/pulumi/sales/demos/aws-ts-webserver/policies
    error: [runtime] Running program '/Users/clstokes/cc/pulumi/sales/demos/aws-ts-webserver/~/cc/pulumi/sales/demos/aws-ts-webserver/policies' failed with an unhandled exception:
        Error: ENOENT: no such file or directory, lstat '/Users/clstokes/cc/pulumi/sales/demos/aws-ts-webserver/~/cc/pulumi/sales/demos/aws-ts-webserver/policies'
        at Object.lstatSync (fs.js:845:3)
        at throwOrPrintModuleLoadError (/Users/clstokes/cc/pulumi/sales/demos/aws-ts-webserver/node_modules/@pulumi/pulumi/cmd/run-policy-pack/run.js:70:21)
        at reportModuleLoadFailure (/Users/clstokes/cc/pulumi/sales/demos/aws-ts-webserver/node_modules/@pulumi/pulumi/cmd/run-policy-pack/run.js:38:5)
        at runProgram (/Users/clstokes/cc/pulumi/sales/demos/aws-ts-webserver/node_modules/@pulumi/pulumi/cmd/run-policy-pack/run.js:214:17)
        at Object.run (/Users/clstokes/cc/pulumi/sales/demos/aws-ts-webserver/node_modules/@pulumi/pulumi/cmd/run-policy-pack/run.js:221:85)
        at v8Hooks.isInitializedAsync.then (/Users/clstokes/cc/pulumi/sales/demos/aws-ts-webserver/node_modules/@pulumi/pulumi/cmd/run-policy-pack/index.js:95:42)
        at process._tickCallback (internal/process/next_tick.js:68:7)
        at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
        at startup (internal/bootstrap/node.js:283:19)
        at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

    error: policy pack /Users/clstokes/cc/pulumi/sales/demos/aws-ts-webserver/~/cc/pulumi/sales/demos/aws-ts-webserver/policies failed to start because of an internal error: could not read plugin [/usr/local/bin/pulumi-analyzer-policy] stdout: EOF

Permalink: https://app.pulumi.com/clstokes/demo-aws-ts-webserver/dev/previews/ef8c30e7-83c8-426a-8a40-ccd339bf7b15
clstokes@Camerons-MacBook-Pro aws-ts-webserver %
```

**Comment by justinvp** [comment]
@clstokes, instead of running `pulumi preview` like:

```sh
pulumi preview --policy-pack=~/cc/pulumi/sales/demos/aws-ts-webserver/policies
```

Does it work for you if you run it as follows (without a `=` between `--policy-pack` and the path)?

```sh
pulumi preview --policy-pack ~/cc/pulumi/sales/demos/aws-ts-webserver/policies
```

(That should allow your shell to expand the path before it gets to the `pulumi` CLI).

**Comment by justinvp** [comment]
Closing. @clstokes, let me know if my suggestion above does not work for you.

**Comment by clstokes** [comment]
@justinvp it does work with the space between the argument and the path.
