### ISSUE TITLE
Panic on failed stack policy

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-policy#200]
Panic:

```
error: preview failed
 
Policy Violations:
panic: fatal: An assertion has failed: Urn is: ''

goroutine 41 [running]:
github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
	/private/tmp/pulumi-20200221-52603-kboq38/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23
github.com/pulumi/pulumi/pkg/util/contract.Assertf(0x0, 0x52cdde7, 0xc, 0xc0017b99d0, 0x1, 0x1)
	/private/tmp/pulumi-20200221-52603-kboq38/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x197
github.com/pulumi/pulumi/pkg/resource.URN.URNName(0x0, 0x0, 0x52c610b, 0x0)
	/private/tmp/pulumi-20200221-52603-kboq38/src/github.com/pulumi/pulumi/pkg/resource/urn.go:82 +0xa5
github.com/pulumi/pulumi/pkg/resource.URN.Name(0x0, 0x0, 0x0, 0xc0017f94a0)
	/private/tmp/pulumi-20200221-52603-kboq38/src/github.com/pulumi/pulumi/pkg/resource/urn.go:111 +0x39
github.com/pulumi/pulumi/pkg/backend/display.(*ProgressDisplay).printPolicyViolations(0xc0000cc840, 0x1)
	/private/tmp/pulumi-20200221-52603-kboq38/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:820 +0x4bb
github.com/pulumi/pulumi/pkg/backend/display.(*ProgressDisplay).processEndSteps(0xc0000cc840)
	/private/tmp/pulumi-20200221-52603-kboq38/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:682 +0x322
github.com/pulumi/pulumi/pkg/backend/display.(*ProgressDisplay).processEvents(0xc0000cc840, 0xc000106370, 0xc000950d20)
	/private/tmp/pulumi-20200221-52603-kboq38/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:1148 +0x153
github.com/pulumi/pulumi/pkg/backend/display.ShowProgressEvents.func1(0xc0000cc840, 0xc000106370, 0xc000950d20, 0xc000bfc360)
	/private/tmp/pulumi-20200221-52603-kboq38/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:286 +0x3f
created by github.com/pulumi/pulumi/pkg/backend/display.ShowProgressEvents
	/private/tmp/pulumi-20200221-52603-kboq38/src/github.com/pulumi/pulumi/pkg/backend/display/progress.go:285 +0x407
```

on policy

```ts
import * as pulumi from "@pulumi/pulumi";
import { PolicyPack, StackValidationPolicy } from "@pulumi/policy";

const stackPolicy: StackValidationPolicy = {
    name: "test-stack-policy",
    description: "Playing with stack policies.",
    enforcementLevel: "mandatory",
    validateStack: (args, reportViolation) => {
        reportViolation("boom");
    },
}

new PolicyPack("aws-eks-unit-tests", {
    policies: [stackPolicy],
});
```

with the stack

```ts
import * as eks from "@pulumi/eks";
import * as awsx from "@pulumi/awsx";

const vpc = new awsx.ec2.Vpc("my-vpc");

// Create a basic EKS cluster.
const cluster = new eks.Cluster("my-cluster", {
    desiredCapacity: 2,
    minSize: 1,
    maxSize: 2,
    storageClasses: "gp2",
    deployDashboard: false,
    version: "1.13",
    vpcId: vpc.id,
    subnetIds: vpc.publicSubnetIds,
});
```

**Comment by justinvp** [comment]
What version of Pulumi CLI?

**Comment by mikhailshilkov** [comment]
```
pulumi version
v1.11.0
```

**Comment by justinvp** [comment]
Looks like a regression introduced by https://github.com/pulumi/pulumi/pull/3881
